[package]
name = "kipr"
version = "0.4.0"
authors = ["Graham King <graham@gkgk.org>"]
edition = "2021"
description = "Manage account details in GPG files"

[dependencies]
anyhow = "1"
clap = { version = "4", features = ["cargo"] }
glob = "0.3"
rpassword = "5.0"
rand = "0.7"
configparser = "3.0.2"
