[package]
name = "kipr"
version = "0.1.0"
authors = ["Graham King <graham@gkgk.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1"
glob = "0.3"
configparser = "1.0.0"
